name: CI

on:
  push:
    branches: [ "main" ]
  schedule:
    # TSİ 09:00, 14:00, 19:00 (UTC 06:00, 11:00, 16:00)
    - cron: "0 6,11,16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          BLOGGER_SITE_TR_ID: ${{ secrets.BLOGGER_SITE_TR_ID }}
          BLOGGER_TOKEN_TR: ${{ secrets.BLOGGER_TOKEN_TR }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: python main.py
