name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up GCP credentials
        run: |
          printf '%s' "${{ secrets.GCLOUD_CREDENTIALS }}" > $HOME/gcloud.json

      - name: Authenticate with GCP
        run: |
          gcloud auth activate-service-account --key-file=$HOME/gcloud.json

      - name: Debug gcloud.json (opsiyonel)
        run: |
          head -n 5 $HOME/gcloud.json

      - name: Run main.py
        run: |
          python3 main.py
